### ISSUE TITLE
Lost Set() while growing

### ISSUE THREAD

**Issue by coraxster** [cornelk/hashmap#46] opened 2019-11-23 13:36 UTC
Hi.  
Check out this branch. It made to reproduce possible lost with set and grow in the same time.  
https://github.com/coraxster/hashmap/commit/fd471c5c4c0691ae94778187c81d6b2ee4a7d86f

**Comment by cornelk** [comment] 2022-08-09 18:02
Thanks for the report. The unit test that confirms this bug has been adapted to the latest generic based version in https://github.com/cornelk/hashmap/commit/806b8bf645ba0ecf58f6d7a2a8730103bdd6c9dd

**Comment by cornelk** [comment] 2022-08-10 05:30
With the fix https://github.com/cornelk/hashmap/pull/61 merged I was not able to reproduce this bug anymore.
Please review and create a new ticket if you see any other issue, thanks!

**Closed by cornelk** 2022-08-10 05:30 UTC
